### ISSUE TITLE
See bonded validators

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#134]
I as a user
Want to see all the validators I have bonded atoms with (and the amount of atoms per validator)
So that I can withdraw my atoms if I want to (and give them to validators I trust more).

AC:
- [x] User is able to see all validators he has bonded atoms with
- [x] User sees all atoms bonded per validator

**Comment by jolesbi** [comment]
since delegating to validator candidates takes place on the client we should store it locally as it happens. 

in the event that there is a bug or the data is erased or disappears for any reason it is possible to query for this information. but we should store it locally by default.

we can include a query button to fetch the data.

**Comment by faboweb** [comment]
See endpoint specification here: https://github.com/cosmos/cosmos-ui/issues/35#issuecomment-348213985
