### ISSUE TITLE
Transaction History Design

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#148]
Current UI:
![image](https://user-images.githubusercontent.com/5869273/33477982-03a526ca-d688-11e7-8980-0cfde1b6f799.png)

Wasn't there already a more sophisticated design by Peng?

**Comment by jolesbi** [comment]
1. is this using the same component as the delegate table?
2. it's missing a bunch of data from #22 right?

**Comment by nylira** [comment]
There isn't a more sophisticated design. I haven't had time to work on it. This is the current design for the transactions page. 

@jolesbi 
1. This is using a custom, ancient component `CardTransaction` -- I think it has to be custom because there are different fields involved.
2. `CardTransaction` has to be updated, but I don't think it's missing a bunch of data. I think the only thing that's missing is the address or contact that the tokens is being sent from/sent to. Do you guys think we should show more data? I think that's enough.

The data from #22 should appear on individual transaction pages, which haven't been designed yet.

I can work on these issues this week.

**Comment by faboweb** [comment]
+1 on showing sender/receiver. I will propose sth..

@jolesbi We will show multiple senders/receivers when it is fully integrated in the SDK (it isn't right now). I will ask about multiple denominations.
