### ISSUE TITLE
Genesis file should be dynamic, not baked in

### ISSUE THREAD

**Issue by nylira** [cosmos/cosmos-ui#2]
Example commands to run with different `genesis.json` files.

`npm run local`
`npm run dev <link to json>`
`npm run testnet <name of testnet in testnets repo>`

We'll need a UI for this later too, but it's not a priority.

**Comment by adrianbrink** [comment]
I think we should have this as a convention:

```
npm run development - starts a local testnet
npm run testnet - connects to a remote testnet, later on you can specify which testnet through a flag
npm run mainnet - connects to a remote mainnet
```

**Comment by adrianbrink** [comment]
And the genesis files for each, except the development, one should be in the binary, so that users don't have to deal with separate genesis files. 

The development genesis file should live in the repository and a user should be able to update it. 

The same applies to keys with money.

## Example 1 
A user runs `npm run development`. The genesis file from the file system gets taken and keys with a lot of default money are written into the correct directory. After that command a user can immediately start to use the UI without having to copy any other files.

## Example 2
A user runs `npm run mainnet`. The UI is initialised with the correct genesis file without user interaction and the UI starts syncing with the mainnet.

**Comment by mappum** [comment]
On the [`testnets`](https://github.com/cosmos/cosmos-ui/tree/testnets) branch, I implemented `npm run testnet [network]` and `npm run local`.

@adrianbrink I like your idea of managing the keys for local testnets to make it easier to start with coins, I'll add that next.

**Comment by mappum** [comment]
Done as of f1fa74d1c885fb0e0eb309fafa0e423cd66516de. Now `npm run local` will start a local testnet, with your client credited with a large balance of coins.
