### ISSUE TITLE
Send Funds

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#21]
As a user
I want to be able to send my tokens to a specified account
so that ... .

AC:
- [x] User is able to send tokens to a specified account
- [x] User is not able to send an amount of tokens he does not posses
- [x] User is not able to send a negative amount of tokens
- [x] User is able to select a token type for the transaction
- [x] User can't send multiple token types at a time
- [x] User is notified if transaction is successful and if it is unsuccessful

Idea:
- Maybe show the balance of the user on the same page
- Maybe update balance live while user types the amount to send

**Comment by nylira** [comment]
Instead of updating the balance live (because the transaction has not occured yet), we'll want to show the pre-transaction amount and post-transaction amount in a new field.

Amount to Send: 1000 ATOM

Balance: 11, 245 ATOM (10,245 ATOM after transaction)

The example could be better, but you get the idea.

**Comment by jolesbi** [comment]
good catch @nylira !

**Comment by jolesbi** [comment]
i think this is done, yeah?

**Comment by nylira** [comment]
It's done!
