### ISSUE TITLE
Tests have a lot of errors not failing the test suite

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#255]
An example:
![image](https://user-images.githubusercontent.com/5869273/34155403-71473ae4-e4b9-11e7-878c-445dc2f9c61e.png)

I will make Jest fail on every console.error called to catched those errors.

**Comment by jolesbi** [comment]
i'm pretty sure all these errors are because of nested dependencies. wallet.js needs node.js which needs rpc etc... 

a bunch of them are also missing the `config.js` module.

i spent some time trying to solve this but didn't have any luck.

lead me to thinking — maybe we ought to be using `shallow()` more often.
