### ISSUE TITLE
mobile menu

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#96]
since this is an electron app (and not a mobile app yet) it feels strange to me that our sidebar disappears into the hamburger menu.

i would propose we keep the sidebar visible at all times on desktop. perhaps it can be less wide.

@nylira

**Comment by nylira** [comment]
I think we should keep the mobile menu. While we're not doing a mobile app yet, some people are going to prefer to run the Cosmos UI in a smaller window on their desktop. Perhaps they just want to monitor the network, or they're waiting on a transaction, or keep updated on the votes of a critical proposal. The sidebar visible below 768px would seriously cut into the usable space of the app window. As the app window goes smaller (say 480px by 480px), it would require us to redesign some main app components because I didn't consider how they would look with the sidebar taking up ~120px of it.

The sidebar does significantly improve app navigation. But I like the flexibility of letting the user resize the app. If the user doesn't want to hide the sidebar, I think they can just keep the app width above 768px. I'm looking at Slack and Discord and they just prevent the app from resizing smaller.

**Comment by faboweb** [comment]
I vote for a responsive design as well. I vote for a removing the electron navigation though.

**Comment by nylira** [comment]
What do you mean by the electron navigation menu? Can you post a screenshot?

**Comment by faboweb** [comment]
![image](https://user-images.githubusercontent.com/5869273/33209097-a48fc528-d114-11e7-83cb-8123428029e1.png)

Only on Windows. I see it is removed on Linux so never mind :)

**Comment by nylira** [comment]
Let's resolve this one then. :)
